# -*- coding: utf-8 -*-
"""Html quick styler

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gE54ZvhZyRNAvn9zCBctmdGhamXm-XyL
"""

!pip install gradio transformers accelerate torch

import gradio as gr
from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

model_id = "ibm-granite/granite-3.3-2b-instruct"

tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForCausalLM.from_pretrained(
    model_id,
    torch_dtype=torch.float16,
    device_map="auto"
)

class ColorPaletteGenerator:

    def __init__(self):
        self.palettes = {
            "modern": {"primary":"#6366F1","secondary":"#8B5CF6","bg":"#0F172A","text":"#ffffff"},
            "ocean": {"primary":"#0284C7","secondary":"#06B6D4","bg":"#0C4A6E","text":"#E0F2FE"},
            "forest": {"primary":"#166534","secondary":"#22C55E","bg":"#052E16","text":"#DCFCE7"},
            "sunset": {"primary":"#F97316","secondary":"#EF4444","bg":"#7C2D12","text":"#FFE4E6"},
            "luxury": {"primary":"#D4AF37","secondary":"#B8860B","bg":"#111111","text":"#F5F5DC"},
            "creative": {"primary":"#EC4899","secondary":"#8B5CF6","bg":"#1E1B4B","text":"#FDF4FF"},
            "vibrant": {"primary":"#E11D48","secondary":"#3B82F6","bg":"#1F2937","text":"#F9FAFB"},
            "minimal": {"primary":"#000000","secondary":"#444444","bg":"#FFFFFF","text":"#111111"},
        }

    def get_palette(self, style):
        return self.palettes.get(style, self.palettes["modern"])

class HTMLPageBuilder:

    def __init__(self, palette):
        self.palette = palette

    def generate_css(self):
        return f"""
        body {{
            margin:0;
            font-family:Arial;
            background:{self.palette['bg']};
            color:{self.palette['text']};
        }}
        header {{
            background:{self.palette['primary']};
            padding:20px;
            text-align:center;
        }}
        section {{
            padding:60px 20px;
            text-align:center;
        }}
        .card {{
            background:{self.palette['secondary']};
            padding:20px;
            margin:10px;
            border-radius:10px;
        }}
        button {{
            background:{self.palette['primary']};
            color:white;
            padding:10px 20px;
            border:none;
            border-radius:5px;
        }}
        """

    def build_page(self, title, description):
        return f"""
        <!DOCTYPE html>
        <html>
        <head>
        <title>{title}</title>
        <style>
        {self.generate_css()}
        </style>
        </head>
        <body>

            <header>
                <h1>{title}</h1>
            </header>

            <section>
                <h2>About</h2>
                <p>{description}</p>
            </section>

            <section>
                <h2>Features</h2>
                <div class="card">AI Generated Content</div>
                <div class="card">Responsive Design</div>
                <div class="card">Modern Styling</div>
            </section>

            <section>
                <h2>Contact</h2>
                <button>Contact Now</button>
            </section>

        </body>
        </html>
        """

# This cell is now empty as its content has been moved to ngD_48PPKTxd to consolidate the Gradio app.

import gradio as gr

# Class definitions
class ColorPaletteGenerator:

    def __init__(self):
        self.palettes = {
            "modern": {"primary":"#6366F1","secondary":"#8B5CF6","bg":"#0F172A","text":"#ffffff"},
            "ocean": {"primary":"#0284C7","secondary":"#06B6D4","bg":"#0C4A6E","text":"#E0F2FE"},
            "forest": {"primary":"#166534","secondary":"#22C55E","bg":"#052E16","text":"#DCFCE7"},
            "sunset": {"primary":"#F97316","secondary":"#EF4444","bg":"#7C2D12","text":"#FFE4E6"},
            "luxury": {"primary":"#D4AF37","secondary":"#B8860B","bg":"#111111","text":"#F5F5DC"},
            "creative": {"primary":"#EC4899","secondary":"#8B5CF6","bg":"#1E1B4B","text":"#FDF4FF"},
            "vibrant": {"primary":"#E11D48","secondary":"#3B82F6","bg":"#1F2937","text":"#F9FAFB"},
            "minimal": {"primary":"#000000","secondary":"#444444","bg":"#FFFFFF","text":"#111111"},
        }

    def get_palette(self, style):
        return self.palettes.get(style, self.palettes["modern"])


class HTMLPageBuilder:

    def __init__(self, palette):
        self.palette = palette

    def generate_css(self):
        return f"""
        body {{
            margin:0;
            font-family:Arial;
            background:{self.palette['bg']};
            color:{self.palette['text']};
        }}
        header {{
            background:{self.palette['primary']};
            padding:20px;
            text-align:center;
        }}
        section {{
            padding:60px 20px;
            text-align:center;
        }}
        .card {{
            background:{self.palette['secondary']};
            padding:20px;
            margin:10px;
            border-radius:10px;
        }}
        button {{
            background:{self.palette['primary']};
            color:white;
            padding:10px 20px;
            border:none;
            border-radius:5px;
        }}
        """

    def build_page(self, title, description):
        return f"""
        <!DOCTYPE html>
        <html>
        <head>
        <title>{title}</title>
        <style>
        {self.generate_css()}
        </style>
        </head>
        <body>

            <header>
                <h1>{title}</h1>
            </header>

            <section>
                <h2>About</h2>
                <p>{description}</p>
            </section>

            <section>
                <h2>Features</h2>
                <div class="card">AI Generated Content</div>
                <div class="card">Responsive Design</div>
                <div class="card">Modern Styling</div>
            </section>

            <section>
                <h2>Contact</h2>
                <button>Contact Now</button>
            </section>

        </body>
        </html>
        """

# Function definition
def generate_html(title, description, color_style):

    palette_obj = ColorPaletteGenerator()
    palette = palette_obj.get_palette(color_style)

    builder = HTMLPageBuilder(palette)
    return builder.build_page(title, description)


# Gradio app setup
with gr.Blocks() as demo:

    gr.Markdown("# HTML Quick-Styler")

    title = gr.Textbox(label="Page Title")
    desc = gr.Textbox(label="Page Description")
    style = gr.Dropdown(
        ["modern","ocean","forest","sunset","luxury","creative","vibrant","minimal"],
        label="Color Style"
    )

    output = gr.HTML()
    btn = gr.Button("Generate Page")

    btn.click(generate_html, inputs=[title,desc,style], outputs=output)

demo.launch(share=True)

